# name: samba

services:
  samba:
    image: crazymax/samba
    container_name: samba
    network_mode: host
    volumes:
      - "./data:/data"
      - "./public:/samba/public"
      - "./share:/samba/share"
      - "./pictures:/samba/pictures"
    environment:
      - "TZ=Asia/Shanghai"
      - "SAMBA_LOG_LEVEL=0"
    restart: always
